// Run with: node scripts/import-alumni.mjs
// Generates scripts/alumni-import.sql — paste into Supabase SQL Editor to import.

import { readFileSync, writeFileSync } from "fs";

const csv = readFileSync("./scripts/alumni.csv", "utf8");
const lines = csv.trim().split("\n").slice(1); // skip header row

const values = lines.map((line) => {
  const parts = line.split(",");
  const lastName = parts[0].trim();
  const firstName = parts[1].trim();
  const degree = parts[2].trim();
  const gradRaw = parts[3].trim();

  // Extract 4-digit year, e.g. "BME 2004" → 2004
  const yearMatch = gradRaw.match(/\d{4}/);
  const year = yearMatch ? parseInt(yearMatch[0], 10) : null;

  // Escape single quotes for SQL
  const esc = (s) => s.replace(/'/g, "''");

  return `  ('${esc(firstName)}', '${esc(lastName)}', '${esc(degree)}', ${year ?? "NULL"}, true)`;
});

const sql = `-- UCF Percussion alumni import
-- Generated by scripts/import-alumni.mjs
-- Paste into Supabase SQL Editor and run.

INSERT INTO public.alumni (first_name, last_name, degree, graduation_year, published)
VALUES
${values.join(",\n")}
ON CONFLICT DO NOTHING;
`;

writeFileSync("./scripts/alumni-import.sql", sql);
console.log(`Done — generated scripts/alumni-import.sql (${values.length} records)`);
